#service.yaml
apiVersion: v1
kind: Service
metadata:
  name: <Name Of the Service> 
spec:
  type: NodePort
  ports:
  - port: 80          # Port exposed within the cluster
    targetPort: 8080  # Port on the pods
    nodePort: 30000   # Port accessible externally on each node
  selector:
    app: example-app  # Select pods with this label
